export const INITIAL_DESTINATIONS = [
  {
    name: 'Kyoto',
    slug: 'kyoto',
    country: 'Japan',
    region: 'Kansai, East Asia',
    description:
      'The cultural heart of Japan, Kyoto boasts thousands of classical Buddhist temples, gardens, imperial palaces, Shinto shrines, and traditional wooden houses.',
    category: 'cultural',
    averageDailyCost: 140,
    currency: 'JPY',
    popularSeason: 'Spring (Cherry Blossoms) / Autumn',
    tags: ['culture', 'temples', 'history', 'food', 'zen', 'walkable'],
    coordinates: { lat: 35.0116, lng: 135.7681 },
    imageUrl:
      'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=1200&q=80',
    rating: 4.9,
    reviewCount: 342,
    isFeatured: true,
    topAttractions: [
      {
        name: 'Fushimi Inari Shrine',
        description: 'Iconic shrine famed for its thousands of vermilion torii gates winding up Mount Inari.',
        estimatedTimeHours: 3,
        costUsd: 0,
        category: 'historical',
      },
      {
        name: 'Kinkaku-ji (Golden Pavilion)',
        description: 'A Zen Buddhist temple whose top two floors are completely covered in gold leaf.',
        estimatedTimeHours: 2,
        costUsd: 4,
        category: 'cultural',
      },
      {
        name: 'Arashiyama Bamboo Grove',
        description: 'Atmospheric bamboo forest with soaring stalks and peaceful walking paths.',
        estimatedTimeHours: 2.5,
        costUsd: 0,
        category: 'nature',
      },
      {
        name: 'Gion Geisha District',
        description: 'Historic district known for preserved machiya merchant houses and teahouses.',
        estimatedTimeHours: 2,
        costUsd: 0,
        category: 'cultural',
      },
    ],
  },
  {
    name: 'Santorini',
    slug: 'santorini',
    country: 'Greece',
    region: 'Cyclades, Southern Europe',
    description:
      'One of the Cyclades islands in the Aegean Sea, renowned for dramatic caldera views, whitewashed buildings, blue-domed churches, and breathtaking sunsets.',
    category: 'beach',
    averageDailyCost: 210,
    currency: 'EUR',
    popularSeason: 'May to October',
    tags: ['romance', 'beaches', 'views', 'sunset', 'wine', 'luxury'],
    coordinates: { lat: 36.3932, lng: 25.4615 },
    imageUrl:
      'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=1200&q=80',
    rating: 4.85,
    reviewCount: 280,
    isFeatured: true,
    topAttractions: [
      {
        name: 'Oia Sunset Walk',
        description: 'Famous cliffside pathway overlooking the Aegean caldera during golden hour.',
        estimatedTimeHours: 2,
        costUsd: 0,
        category: 'sightseeing',
      },
      {
        name: 'Red Beach',
        description: 'Unique volcanic red rock beach with crystal clear waters.',
        estimatedTimeHours: 3,
        costUsd: 0,
        category: 'nature',
      },
      {
        name: 'Akrotiri Archaeological Site',
        description: 'Minoan Bronze Age settlement preserved under volcanic ash.',
        estimatedTimeHours: 2,
        costUsd: 12,
        category: 'historical',
      },
    ],
  },
  {
    name: 'Reykjavik & Golden Circle',
    slug: 'reykjavik',
    country: 'Iceland',
    region: 'Northern Europe',
    description:
      'The gateway to Iceland’s otherworldly landscapes, featuring geothermal lagoons, active geysers, thundering waterfalls, and the magical Northern Lights.',
    category: 'adventure',
    averageDailyCost: 240,
    currency: 'ISK',
    popularSeason: 'Summer (Midnight Sun) / Winter (Auroras)',
    tags: ['adventure', 'nature', 'waterfalls', 'geothermal', 'aurora', 'glaciers'],
    coordinates: { lat: 64.1466, lng: -21.9426 },
    imageUrl:
      'https://images.unsplash.com/photo-1504893524553-b855bce32c67?auto=format&fit=crop&w=1200&q=80',
    rating: 4.92,
    reviewCount: 195,
    isFeatured: true,
    topAttractions: [
      {
        name: 'Gullfoss Waterfall',
        description: 'Iconic multi-step waterfall plunging dramatically into a rugged canyon.',
        estimatedTimeHours: 2,
        costUsd: 0,
        category: 'nature',
      },
      {
        name: 'Blue Lagoon Spa',
        description: 'Mineral-rich geothermal waters nestled in a volcanic lava field.',
        estimatedTimeHours: 4,
        costUsd: 75,
        category: 'relaxation',
      },
      {
        name: 'Thingvellir National Park',
        description: 'UNESCO heritage rift valley where Eurasian and North American plates meet.',
        estimatedTimeHours: 3,
        costUsd: 0,
        category: 'historical',
      },
    ],
  },
  {
    name: 'Banff National Park',
    slug: 'banff',
    country: 'Canada',
    region: 'Alberta, North America',
    description:
      'Canada’s first national park in the heart of the Rocky Mountains, featuring turquoise glacial lakes, towering alpine peaks, wildlife, and pristine wilderness trails.',
    category: 'nature',
    averageDailyCost: 175,
    currency: 'CAD',
    popularSeason: 'June to September / Winter for Skiing',
    tags: ['mountains', 'hiking', 'nature', 'lakes', 'wildlife', 'skiing'],
    coordinates: { lat: 51.1784, lng: -115.5708 },
    imageUrl:
      'https://images.unsplash.com/photo-1503614472-8c93d56e92ce?auto=format&fit=crop&w=1200&q=80',
    rating: 4.95,
    reviewCount: 410,
    isFeatured: true,
    topAttractions: [
      {
        name: 'Lake Louise & Moraine Lake',
        description: 'World-famous brilliant turquoise glacier-fed lakes encircled by soaring peaks.',
        estimatedTimeHours: 5,
        costUsd: 15,
        category: 'nature',
      },
      {
        name: 'Banff Gondola & Sulphur Mountain',
        description: 'Scenic aerial tramway offering 360-degree views of six mountain ranges.',
        estimatedTimeHours: 2.5,
        costUsd: 55,
        category: 'sightseeing',
      },
    ],
  },
  {
    name: 'Rome',
    slug: 'rome',
    country: 'Italy',
    region: 'Southern Europe',
    description:
      'The Eternal City combines nearly three millennia of globally influential art, architecture, and culture with vibrant street life and extraordinary culinary traditions.',
    category: 'city',
    averageDailyCost: 160,
    currency: 'EUR',
    popularSeason: 'April to June / September to October',
    tags: ['history', 'food', 'art', 'museums', 'architecture', 'walkable'],
    coordinates: { lat: 41.9028, lng: 12.4964 },
    imageUrl:
      'https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=1200&q=80',
    rating: 4.88,
    reviewCount: 520,
    isFeatured: true,
    topAttractions: [
      {
        name: 'Colosseum & Roman Forum',
        description: 'Immense stone amphitheater and heart of ancient Roman political life.',
        estimatedTimeHours: 3.5,
        costUsd: 22,
        category: 'historical',
      },
      {
        name: 'Vatican Museums & Sistine Chapel',
        description: 'Renaissance masterpieces including Michelangelo’s celebrated ceiling frescoes.',
        estimatedTimeHours: 4,
        costUsd: 25,
        category: 'cultural',
      },
      {
        name: 'Trevi Fountain & Pantheon',
        description: 'Baroque masterpiece fountain and remarkably preserved Roman dome.',
        estimatedTimeHours: 2,
        costUsd: 5,
        category: 'sightseeing',
      },
    ],
  },
  {
    name: 'Bali',
    slug: 'bali',
    country: 'Indonesia',
    region: 'Southeast Asia',
    description:
      'The Island of the Gods offers lush jungle terraces in Ubud, sacred coastal sea temples, world-class surf breaks, rejuvenating yoga retreats, and warm hospitality.',
    category: 'beach',
    averageDailyCost: 75,
    currency: 'IDR',
    popularSeason: 'April to October',
    tags: ['tropical', 'wellness', 'surfing', 'culture', 'budget', 'relaxation'],
    coordinates: { lat: -8.3405, lng: 115.092 },
    imageUrl:
      'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=1200&q=80',
    rating: 4.79,
    reviewCount: 390,
    isFeatured: true,
    topAttractions: [
      {
        name: 'Tegalalang Rice Terraces',
        description: 'Scenic cascading green rice paddies with jungle swings and walking trails.',
        estimatedTimeHours: 2.5,
        costUsd: 3,
        category: 'nature',
      },
      {
        name: 'Tanah Lot & Uluwatu Temples',
        description: 'Ancient sea temples perched on ocean cliffs featuring traditional Kecak dance.',
        estimatedTimeHours: 3,
        costUsd: 5,
        category: 'cultural',
      },
    ],
  },
];
